#The database is connected through the Docker compose file:

version: '3.8'

services:
  db:
    image: postgres:15
    container_name: "container_name"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


  #With the terminal:

  cd Desktop
  cd "path your compose-file"
  Docker compose up -d